query spaceRolesL0 {
  spaces(filter: { visibilities: [ACTIVE, DEMO] }) {
    id
    nameID
    about {
      profile {
        displayName
        tagline
        location {
          country
          city
        }
        url
      }
    }
    community {
      roleSet {
        memberUsers: usersInRole(role: MEMBER) {
          id
        }
        memberOrganizations: organizationsInRole(role: MEMBER) {
          id
        }
        leadOrganizations: organizationsInRole(role: LEAD) {
          id
        }
        leadUsers: usersInRole(role: LEAD) {
          id
        }
      }
    }
    account {
      host {
        id
      }
    }
  }
}
